-- create table public.users (
-- id bigint generated by default as identity not null,
-- username text not null default ''::text,
-- email text null default ''::text,
-- password character varying null default ''::character varying,
-- role text null,
-- constraint Users_pkey primary key (id),
-- constraint Users_role_check check ((length(role) < 50))
-- ) TABLESPACE pg_default;

-- create table public.services (
--   id bigint generated by default as identity not null,
--   title text not null,
--   description text null,
--   image text null,
--   constraint services_pkey primary key (id)
-- ) TABLESPACE pg_default;

-- create table public.reviews (
--   id bigint generated by default as identity not null,
--   customer_name character varying not null,
--   rating integer null,
--   review text null,
--   user_id bigint null,
--   constraint reviews_pkey primary key (id),
--   constraint reviews_user_id_fkey foreign KEY (user_id) references users (id) on delete set null
-- ) TABLESPACE pg_default;

-- create table public.quotations (
--   id bigint generated by default as identity not null,
--   customer_name text not null,
--   email character varying null,
--   phone bigint null,
--   project_type text null,
--   project_details text null,
--   user_id bigint null,
--   constraint quotations_pkey primary key (id),
--   constraint quotations_user_id_fkey foreign KEY (user_id) references users (id) on delete set null
-- ) TABLESPACE pg_default;

-- create table public.portfolio (
--   id bigint generated by default as identity not null,
--   project_name text not null,
--   category character varying null,
--   description text null,
--   image text null,
--   status text null,
--   service_id bigint null,
--   constraint portfolio_pkey primary key (id),
--   constraint portfolio_service_id_fkey foreign KEY (service_id) references services (id) on delete set null
-- ) TABLESPACE pg_default;

-- create table public.contacts (
--   id bigint generated by default as identity not null,
--   name text not null,
--   email character varying null,
--   phone bigint null,
--   message text null,
--   constraint contacts_pkey primary key (id)
-- ) TABLESPACE pg_default;

ALTER TABLE users 
  ALTER COLUMN id TYPE UUID USING gen_random_uuid();

-- updating the rls policies for the users table to use UUID instead of bigint
CREATE POLICY "Users can manage their own data" ON users 
    FOR ALL USING (auth.uid() = id);


-- Quotations access rules:
CREATE POLICY "Users can view their own quotations" ON quotations 
    FOR SELECT USING (auth.uid() = user_id OR (auth.jwt() ->> 'role') IN ('Admin', 'Manager'));