// ============================================================
// Portfolio Mock Data
// Edit this file to update project listings and gallery images
// ============================================================

export const completedProjects = [
  {
    id: "cp-1",
    title: "The Emerald Heights Skyscraper",
    category: "Commercial",
    location: "Manhattan, NY",
    description: "A 45-story commercial skyscraper featuring sustainable double-glazed panels and intelligent climate integration systems.",
    completionStatus: "Completed",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=900",
    year: 2024,
    client: "Emerald Holdings Group",
    tags: ["Skyscraper", "Sustainable", "LEED"],
  },
  {
    id: "cp-2",
    title: "Bespoke Glass Villa",
    category: "Residential",
    location: "Hamptons, NY",
    description: "Luxury eco-residence constructed with local pine beams, structural concrete, and solar glass roofing panels.",
    completionStatus: "Completed",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=900",
    year: 2023,
    client: "Sterling Family Trust",
    tags: ["Luxury", "Eco-Friendly", "Glass"],
  },
  {
    id: "cp-3",
    title: "Eco-Industrial Complex",
    category: "Industrial",
    location: "Brooklyn, NY",
    description: "LEED Platinum certified factory building with integrated rainwater harvesting systems and passive cooling ventilation.",
    completionStatus: "Completed",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=900",
    year: 2025,
    client: "Aura Logistics Ltd",
    tags: ["Industrial", "LEED Platinum", "Sustainable"],
  },
  {
    id: "cp-4",
    title: "The Meridian Office Park",
    category: "Commercial",
    location: "Jersey City, NJ",
    description: "A modern multi-tenant office campus featuring biophilic design principles, smart building systems, and rooftop gardens.",
    completionStatus: "Completed",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=900",
    year: 2023,
    client: "Meridian Properties Corp",
    tags: ["Office", "Biophilic", "Smart Building"],
  },
  {
    id: "cp-5",
    title: "Riverside Luxury Condominiums",
    category: "Residential",
    location: "Hoboken, NJ",
    description: "A 22-floor luxury residential tower with premium waterfront views, concierge amenities, and green roof terraces.",
    completionStatus: "Completed",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=900",
    year: 2022,
    client: "Riverside Realty Partners",
    tags: ["Condominiums", "Luxury", "Waterfront"],
  },
  {
    id: "cp-6",
    title: "Skybridge Pedestrian Connector",
    category: "Civil Engineering",
    location: "Newark, NJ",
    description: "A 240-meter elevated pedestrian skybridge connecting two commercial districts with tensioned steel cable architecture.",
    completionStatus: "Completed",
    image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?q=80&w=900",
    year: 2024,
    client: "Newark City Urban Development",
    tags: ["Bridge", "Civil", "Steel"],
  },
];

export const ongoingProjects = [
  {
    id: "op-1",
    title: "Zenith Corporate Tower",
    category: "Commercial",
    location: "Midtown, NY",
    description: "A 60-story mixed-use supertall featuring Class-A office floors, sky lounges, and an integrated vertical urban farm.",
    completionStatus: "In Progress",
    progress: 65,
    phase: "Structural Framing",
    image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=900",
    year: 2026,
    client: "Zenith Capital Group",
    tags: ["Supertall", "Mixed-Use", "Vertical Farm"],
  },
  {
    id: "op-2",
    title: "Aurora Eco-Village",
    category: "Residential",
    location: "Queens, NY",
    description: "A 48-unit sustainable housing community built with cross-laminated timber, solar panels, and shared communal gardens.",
    completionStatus: "In Progress",
    progress: 40,
    phase: "Foundation & Framing",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=900",
    year: 2027,
    client: "Aurora Living Foundation",
    tags: ["Sustainable", "Timber", "Community"],
  },
  {
    id: "op-3",
    title: "Harbor Point Cultural Center",
    category: "Public Infrastructure",
    location: "Staten Island, NY",
    description: "A civic arts and cultural hub featuring a 1,200-seat performance hall, exhibition galleries, and public waterfront promenade.",
    completionStatus: "In Progress",
    progress: 25,
    phase: "Foundation Excavation",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=900",
    year: 2028,
    client: "Staten Island Arts Commission",
    tags: ["Cultural", "Public", "Performance Hall"],
  },
];

export const residentialProjects = [
  {
    id: "rp-1",
    title: "Bespoke Glass Villa",
    category: "Residential",
    location: "Hamptons, NY",
    description: "Luxury eco-residence with local pine beams, structural concrete, and solar glass roofing.",
    completionStatus: "Completed",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=900",
    year: 2023,
    client: "Sterling Family Trust",
    tags: ["Villa", "Luxury", "Eco-Friendly"],
  },
  {
    id: "rp-2",
    title: "Riverside Luxury Condominiums",
    category: "Residential",
    location: "Hoboken, NJ",
    description: "22-floor luxury tower with waterfront views, concierge amenities, and rooftop green terraces.",
    completionStatus: "Completed",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=900",
    year: 2022,
    client: "Riverside Realty Partners",
    tags: ["Tower", "Luxury", "Waterfront"],
  },
  {
    id: "rp-3",
    title: "Lakeside Minimalist Retreat",
    category: "Residential",
    location: "Upstate, NY",
    description: "A single-family minimalist home with floor-to-ceiling glass walls, cantilevered roofline, and private lakefront dock.",
    completionStatus: "Completed",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=900",
    year: 2023,
    client: "Private Client",
    tags: ["Minimalist", "Lakefront", "Glass"],
  },
  {
    id: "rp-4",
    title: "Aurora Eco-Village",
    category: "Residential",
    location: "Queens, NY",
    description: "48-unit sustainable housing community built with cross-laminated timber and solar-integrated facades.",
    completionStatus: "In Progress",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=900",
    year: 2027,
    client: "Aurora Living Foundation",
    tags: ["Community", "CLT", "Sustainable"],
  },
];

export const commercialProjects = [
  {
    id: "coml-1",
    title: "The Emerald Heights Skyscraper",
    category: "Commercial",
    location: "Manhattan, NY",
    description: "45-story commercial skyscraper with sustainable double-glazed panels and intelligent climate integration.",
    completionStatus: "Completed",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=900",
    year: 2024,
    client: "Emerald Holdings Group",
    tags: ["Skyscraper", "Sustainable", "LEED"],
  },
  {
    id: "coml-2",
    title: "The Meridian Office Park",
    category: "Commercial",
    location: "Jersey City, NJ",
    description: "Multi-tenant office campus featuring biophilic design, smart building systems, and rooftop gardens.",
    completionStatus: "Completed",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=900",
    year: 2023,
    client: "Meridian Properties Corp",
    tags: ["Office Park", "Biophilic", "Smart"],
  },
  {
    id: "coml-3",
    title: "Zenith Corporate Tower",
    category: "Commercial",
    location: "Midtown, NY",
    description: "60-story mixed-use supertall with Class-A office floors, sky lounges, and vertical urban farm.",
    completionStatus: "In Progress",
    image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=900",
    year: 2026,
    client: "Zenith Capital Group",
    tags: ["Supertall", "Mixed-Use", "Urban"],
  },
  {
    id: "coml-4",
    title: "Grand Atrium Shopping Centre",
    category: "Commercial",
    location: "Bronx, NY",
    description: "A contemporary three-level retail and dining complex built around a 28-meter sky-lit central atrium.",
    completionStatus: "Completed",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=900",
    year: 2022,
    client: "Grand Commerce LLC",
    tags: ["Retail", "Atrium", "Shopping"],
  },
];

export const galleryImages = [
  {
    id: "gal-1",
    url: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=1200",
    title: "Commercial Concrete Formwork",
    category: "Structural",
    description: "Precision reinforced concrete formwork during the foundation phase of a major commercial development.",
  },
  {
    id: "gal-2",
    url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200",
    title: "Glazed Skyscraper Facade",
    category: "Commercial",
    description: "Thermal-insulated glass panel installation on the Emerald Heights 45-story tower.",
  },
  {
    id: "gal-3",
    url: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=1200",
    title: "Bespoke Timber Framing",
    category: "Residential",
    description: "Exposed local pine beams supporting the high-vaulted ceiling of a private villa.",
  },
  {
    id: "gal-4",
    url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200",
    title: "Modern Glass Villa Exterior",
    category: "Residential",
    description: "Completed exterior view of a Hamptons glass villa featuring reflection-coated facades.",
  },
  {
    id: "gal-5",
    url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200",
    title: "Bespoke Living Interior",
    category: "Interior",
    description: "A warm minimalistic living room combining structural concrete with precision timber accents.",
  },
  {
    id: "gal-6",
    url: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200",
    title: "Corporate Lobby Atrium",
    category: "Commercial",
    description: "Double-height lobby atrium with full-height glazing and a green wall installation.",
  },
  {
    id: "gal-7",
    url: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1200",
    title: "Industrial Ventilation Grid",
    category: "Industrial",
    description: "Smart passive ventilation ductwork installation inside the Eco-Industrial complex.",
  },
  {
    id: "gal-8",
    url: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?q=80&w=1200",
    title: "Skybridge Steel Assembly",
    category: "Civil Engineering",
    description: "Tensioned steel cable assembly during the Skybridge Pedestrian Connector project.",
  },
];
